### ISSUE TITLE
401 Response Code

### ISSUE THREAD

**Issue by benaneesh** [nneal/snapcat#21]
Interesting gem, and great job nneal! But i keep getting 401 responses when I try to send media or add a friend. 

    #<Snapcat::Response:0x007ff6d115b510 @code=401, @data={:media_id=>"USERNAME~123456789"}, @http_success=false>

I did initialize the client with my login details.
```ruby
snapcat = Snapcat::Client.new('your-username')
snapcat.login('topsecretpassword')
snapcat.auth_token #=> "2a9a117b-855b-449a-9cec-eaccac6fa87f"
```

**Comment by nneal** [comment]
thanks dude, and sorry it took so long to respond. Here is a possible solution (should be merged to master soon) https://github.com/nneal/snapcat/issues/26
