### ISSUE TITLE
401

### ISSUE THREAD

**Issue by ValkyrieUK** [nneal/snapcat#26]
Looks like its just getting 401's back

**Comment by toddwschneider** [comment]
@ValkyrieUK @nneal I believe I fixed this issue by setting a few headers, see here: https://github.com/toddwschneider/snapcat/commit/a0e4abaa24de58d934264ebed277ec91ccb147b4

**Comment by nneal** [comment]
Thanks Todd, that makes sense. I considered spoofing headers but it wasn't necessary at the time. Want to submit that as a PR? 

(Please add those headers to the `request_media` method too, prob best to throw the header hash into a method of its own too)

**Comment by toddwschneider** [comment]
@nneal no problem, see here: https://github.com/nneal/snapcat/pull/27

**Comment by nneal** [comment]
Closing this, please let me know if the error still pops up. Thanks @toddwschneider for fixing!

**Comment by ValkyrieUK** [comment]
Fantastic cheers
